Hw02 unpack string
Dendyator/1 pull request #3
Opened 2024-02-22 14:55 UTC by Dendyator

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-02-27 11:18 UTC, agneum requested changes
Спасибо за вариант решения, однако есть критичные замечания
Возвращаю задачу на доработку

2024-02-27 11:18 UTC, agneum commented on hw02_unpack_string/unpack.go
> +var lastLetter string
Почему эти переменные глобальные?

2024-02-27 11:18 UTC, agneum commented on hw02_unpack_string/unpack.go
> +	}
Есть ли более простой способ определить, что строка содержит только число?

2024-02-27 11:18 UTC, agneum commented on hw02_unpack_string/unpack.go
> +	if strings.IndexRune("0123456789", part[0]) != -1 { //nolint:gosimple
Замечания линтера следует исправить, а не игнорировать

2024-02-27 11:18 UTC, agneum commented on hw02_unpack_string/unpack.go
> +			letter = remove(letter)
Выглядит неоптимально. Рекомендую записывать символ(-ы) только, когда понятно, что они действительно должы быть в итоговой строке

2024-02-27 11:18 UTC, agneum commented on hw02_unpack_string/unpack.go
> +	a := strings.Join(letter, "")
Рекомендую использовать `strings.Builder`

2024-02-27 11:28 UTC, Dendyator commented on hw02_unpack_string/unpack.go
> +	if strings.IndexRune("0123456789", part[0]) != -1 { //nolint:gosimple
Линтер предлагает совсем другую функцию, которая мне не подходит в данном случае

2024-02-27 11:35 UTC, Dendyator commented on hw02_unpack_string/unpack.go
> +	}
Если бы я его знал, я бы безусловно его использовал

2024-02-27 12:11 UTC, Dendyator commented on hw02_unpack_string/unpack.go
> +			letter = remove(letter)
Не очень понятно. Если бы я сохранял нужные символы в новом слайсе, а потом добавлял бы их в целевой на шаге вместе с функцией lastletter - это было бы лучше?

2024-02-27 13:02 UTC, Dendyator commented on hw02_unpack_string/unpack.go
> +	a := strings.Join(letter, "")
https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#%D0%B3%D0%B4%D0%B5-%D0%BF%D0%BE%D1%81%D0%BC%D0%BE%D1%82%D1%80%D0%B5%D1%82%D1%8C-%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D1%81%D0%BA%D0%BE%D0%B5-%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D0%B5

2024-02-28 03:44 UTC, agneum approved these changes
Спасибо за правки.
Итого: 8 баллов из 10. Принято

2024-02-28 03:44 UTC, agneum commented on hw02_unpack_string/unpack.go
> +	}
Можно использовать https://pkg.go.dev/strconv#Atoi или https://pkg.go.dev/unicode#IsDigit
Можно проверить, что руна находится в диапазоне между 0 и 9
Можно составить одно регулярное выражение, которое проверяет, что в строке только цифры

Либо проверять в цикле, отдельной проверки для этого не требуется

2024-02-28 03:44 UTC, agneum commented on hw02_unpack_string/unpack.go
> +	if strings.IndexRune("0123456789", part[0]) != -1 { //nolint:gosimple
Тем не менее, рекомендую использовать предложенные выше способы для определения числа

2024-02-28 03:44 UTC, agneum commented on hw02_unpack_string/unpack.go
> +			letter = remove(letter)
Можно не использовать слайс совсем. Достаточно запоминать предыдущую руну и добавлять в результат только нужные символы

2024-02-28 03:44 UTC, agneum commented on hw02_unpack_string/unpack.go
> +	letter = nil //nolint
Эта строка, вероятно, не нужна

2024-02-29 17:01 UTC, merged