Hw03 frequency analysis
Dendyator/1 pull request #4
Opened 2024-02-29 13:32 UTC by Dendyator

Домашнее задание №3 «Частотный анализ»
Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
 Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
 Я запустил go mod tidy.
 Я удалил .sync файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
Критерии оценки
 Пайплайн зелёный - 4 балла
 Добавлены новые юнит-тесты - до 4 баллов
 Понятность и чистота кода - до 2 баллов
Зачёт от 7 баллов

2024-02-29 15:08 UTC, agneum requested changes
Спасибо за вариант решения.
Возвращаю задачу на доработку, поскольку не хватает новых юнит-тестов и содержатся существенные замечания
Итого: 4 балла из 10.

2024-02-29 15:08 UTC, agneum commented on hw03_frequency_analysis/top.go
> +	a := make([][2]string, 0, len(scoreMap))
Для хранения слова и счётчика рекомендую использовать структуру с полями соответствующих типов, иначе результаты при сравнении получатся некорректными

2024-02-29 15:08 UTC, agneum commented on hw03_frequency_analysis/top.go
> +	a = a[:10]
Если в слайсе нет 10 элементов, будет паника

2024-02-29 15:08 UTC, agneum commented on hw03_frequency_analysis/top.go
> +	return result
Не хватает новых юнит-тестов

2024-02-29 16:58 UTC, Dendyator commented on hw03_frequency_analysis/top.go
> +	return result
добавил

2024-02-29 16:58 UTC, Dendyator commented on hw03_frequency_analysis/top.go
> +	a = a[:10]
вылечил

2024-02-29 16:59 UTC, Dendyator commented on hw03_frequency_analysis/top.go
> +	a := make([][2]string, 0, len(scoreMap))
не очень понятно замечание - я же наполняю массив стрингами - один изначально стринг, второй через strconv.Itoa

2024-03-01 03:09 UTC, agneum requested changes

2024-03-01 03:09 UTC, agneum commented on hw03_frequency_analysis/top.go
> +	a := make([][2]string, 0, len(scoreMap))
> я же наполняю массив стрингами
В этом и проблема по двум причинам.
1. Сравнение счётчиков в виде строк даст некорректный результат. Например, строка "2" окажется больше, чем "10". Язык предоставляет набор простых встроенных типов данных, которые рекомендуется использовать.
2. Разные по сути и предназначению сущности (слово и счётчик) хранятся в одном и том же массиве. Это увеличивает вероятность ошибок и увеличивает когнитивную сложность

2024-03-02 14:41 UTC, agneum requested changes
Спасибо за правки, однако пайплайн всё ещё не успешный.
Возможно, указанная версия линтера не работает корректно с параметрическими типами, которые используются в пакете `cmp`. Предложил бы обновить версию линетра, либо не использовать пакет `cmp`

2024-03-02 14:41 UTC, agneum commented on hw03_frequency_analysis/go.mod
> +module example.com/m/v2
Рекомендую указать полный путь до модуля в репозитории

2024-03-02 14:41 UTC, agneum commented on hw03_frequency_analysis/top.go
> +		return cmp.Compare(a.word, b.word)
Для сравнения значений одного типа можно использовать знаки `>`, `<`

2024-03-03 08:04 UTC, Dendyator commented on hw03_frequency_analysis/go.mod
> +module example.com/m/v2
Изменил

2024-03-03 08:05 UTC, Dendyator commented on hw03_frequency_analysis/top.go
> +		return cmp.Compare(a.word, b.word)
https://pkg.go.dev/cmp#Compare

2024-03-03 08:08 UTC, Dendyator commented
Линтер в IDE (golangci-lint has version 1.55.2 built with go1.21.3 from e3c2265f on 2023-11-03T12:59:25Z) отрабатывает корректно и никаких ошибок не выдает.
Ругается линтер в https://github.com/Dendyator/1/actions/runs/8128716928/job/22214906659 и каким образом его там обновлять я понятия не имею. 
Не использовать пакет cmp (предлагаемый стандартной библиотекой го https://pkg.go.dev/slices#SortFunc) из-за непонятной ошибки какого-то непонятного линтера, не считаю целесообразным.
ПС1. Почему не засчитывается создание новых юнит тестов?
ПС2. Какие именно замечания имеются к чистоте и понятности кода?
ПС3. Написал новый код для HW2, прошу проверить.

2024-03-03 12:33 UTC, agneum commented on hw03_frequency_analysis/top.go
> +		return cmp.Compare(a.word, b.word)
https://go.dev/ref/spec#Operators_and_punctuation

2024-03-03 12:34 UTC, agneum commented
> Линтер в IDE (golangci-lint has version 1.55.2 built with go1.21.3 from e3c2265f on 2023-11-03T12:59:25Z) отрабатывает корректно и никаких ошибок не выдает. 

Отлично, это означает, что обновление версии поможет исправить ошибку.

> и каким образом его там обновлять я понятия не имею

Появилась хорошая возможность научиться. Версия линтера в этом репозитории указывается в конфигурации GitHub Actions: https://github.com/Dendyator/1/blob/master/.github/workflows/tests.yml

> не считаю целесообразным

ок

> ПС1. Почему не засчитывается создание новых юнит тестов? 

Похоже, утверждение не соответствует действительности. На чём основывается данное суждение?

> ПС2. Какие именно замечания имеются к чистоте и понятности кода?

Все замечания указаны в комментариях к PR

2024-03-03 13:31 UTC, Dendyator commented
Спасибо за вариант решения.
      Возвращаю задачу на доработку, поскольку не хватает новых юнит-тестов и содержатся существенные замечания
      Итого: 4 балла из 10.

Изначально про новые юнит-тесты я вообще забыл и после этого замечания их добавил, однако оценка никак не изменилась, поэтому последовал резонный вопрос почему они не засчитаны.

2024-03-03 14:03 UTC, Dendyator commented
Появилась хорошая возможность научиться. Версия линтера в этом репозитории указывается в конфигурации GitHub Actions: https://github.com/Dendyator/1/blob/master/.github/workflows/tests.yml

Спасибо за помощь, обновил, линтер перестал ругаться

2024-03-04 01:51 UTC, agneum approved these changes
Спасибо за правки. Принято

2024-10-10 08:42 UTC, merged