HW4 is complete
Dendyator/1 pull request #6
Opened 2024-03-25 11:13 UTC by Dendyator

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-03-27 04:29 UTC, dshemin requested changes

2024-03-27 04:29 UTC, dshemin commented on hw04_lru_cache/list_test.go
> +		l.PushFront(11) // [11, 70, 50, 10, 20, 30, 600]
Важно:

Было бы не плохо проверять состояние списка после каждой операции чтобы зафиксировать наши предположения не в комментариях, а в коде теста.

2024-03-27 04:29 UTC, dshemin commented on hw04_lru_cache/list.go
> +func (l *list) Init() *list {
Важно:

Данная функция точно должна быть экспортируемой?

2024-03-27 04:29 UTC, dshemin commented on hw04_lru_cache/list.go
> +	l.root.next = &l.root
Важно:

В итоге список закольцуется. Если сразу после создания запустить итерацию по такому списку то мы зациклимся навечно так, как голова ссылается на саму себя.

2024-03-27 04:29 UTC, dshemin commented on hw04_lru_cache/list.go
> +	l.root.prev = &l.root
Важно:

Довольно необычное решение. Чаще всего в списках объявляют два указателя: на голову и хвост. Так сделать - более удачное решение, тому, кто будет поддерживать код, будет легче.

2024-03-27 04:29 UTC, dshemin commented on hw04_lru_cache/list.go
> +	if l.len == 0 {
Важно:

Если не закальцовывать, то не надо будет делать эту проверку.

2024-03-27 04:29 UTC, dshemin commented on hw04_lru_cache/list.go
> +func (l *list) lazyInit() {
Важно:

Зачем нам данная функция? Нам лучше гарантировать что список у нас будет создаваться всегда правильно.

2024-03-27 04:29 UTC, dshemin commented on hw04_lru_cache/cache_test.go
> +		c := NewCache(5)
Критично:

Не все требуемые тесты реализованы. Обратите внимание на текст задания:

```
Ожидаются следующие тесты:
- на логику выталкивания элементов из-за размера очереди
(например: n = 3, добавили 4 элемента - 1й из кэша вытолкнулся);
- на логику выталкивания давно используемых элементов
(например: n = 3, добавили 3 элемента, обратились несколько раз к разным элементам:
изменили значение, получили значение и пр. - добавили 4й элемент,
из первой тройки вытолкнется тот элемент, что был затронут наиболее давно).
```

2024-03-27 04:29 UTC, dshemin commented on hw04_lru_cache/cache.go
> +	c.items = map[string]*cacheMapElement{}
Важно:

Тут надо очистить и список тоже.

2024-03-27 04:29 UTC, dshemin commented on hw04_lru_cache/cache.go
> +	sync.RWMutex
Важно:

Не встраивайте mutex. В таком случае все методы мютекса становятся доступны на вашем кеше. Если бы структура была экспортируемой, то любой бы мог напрямую вызвать Lock() и сломать кеш.

2024-03-28 09:50 UTC, Dendyator commented on hw04_lru_cache/list.go
> +	l.root.next = &l.root
здесь и далее сделано по образцу пакета list стандартной библиотеки го. 
https://cs.opensource.google/go/go/+/refs/tags/go1.22.1:src/container/list/list.go
если там не совсем оптимальное решение, то прошу подсказать где его искать

2024-03-28 09:51 UTC, Dendyator commented on hw04_lru_cache/list_test.go
> +		l.PushFront(11) // [11, 70, 50, 10, 20, 30, 600]
добавил

2024-03-28 09:51 UTC, Dendyator commented on hw04_lru_cache/list.go
> +func (l *list) Init() *list {
изменил

2024-03-28 09:51 UTC, Dendyator commented on hw04_lru_cache/cache.go
> +	c.items = map[string]*cacheMapElement{}
+

2024-03-28 09:55 UTC, Dendyator commented on hw04_lru_cache/cache.go
> +	sync.RWMutex
Если не встраивать мьютексы, то не проходит последний тест из списка 
"func TestCacheMultithreading(t *testing.T) {
	c := NewCache(10)
	wg := &sync.WaitGroup{}
	wg.Add(2)
	..."
	
	Какой выход из этой ситуации?

2024-03-28 09:56 UTC, Dendyator commented on hw04_lru_cache/cache_test.go
> +		c := NewCache(5)
Добавил

2024-03-29 05:53 UTC, dshemin commented on hw04_lru_cache/cache.go
> +	sync.RWMutex
Надо не всторить в кеш, а сделать его свойством. Переписать так:
```
mx sync.Mutex
```

2024-03-29 06:08 UTC, dshemin commented on hw04_lru_cache/list.go
> +	l.root.next = &l.root
Вот пример https://dzen.ru/a/ZYC3sH6XmGwKww2s

2024-03-29 06:11 UTC, dshemin approved these changes

2024-03-29 06:11 UTC, dshemin commented on hw04_lru_cache/cache.go
> +	c.items = map[string]*cacheMapElement{}
Если сделать так, то после отчистки, при попытке добавить в кеш, мы будем разыменовывать nil - не очень хорошо. Просто создайте новый список через NewList

2024-11-26 14:27 UTC, merged